// src/lib/components/FileDropper.svelte
<script lang="ts">
	import { FileParser } from '$lib/FileParser.ts';

	enum DropState {
		None = '',
		Dropping = 'DropZoneHover',
		Dropped = 'DropZoneComplete'
	}

	let state = DropState.None;
	let fileParser = new FileParser();

	export let preDrop = () => {};
	export let dropCallback = (res: string) => {};
	export let fileParserCallback = (res: string) => {};

	function handleDrag(event: Event) {
		event.preventDefault();

		switch (event.type) {
			case 'dragover':
				state = DropState.Dropping;
				break;
			case 'dragexit':
				state = DropState.None;
				break;

			default:
				break;
		}
	}

	async function handleDrop(event: DragEvent) {
		event.preventDefault();

		state = DropState.None;
		
		if ( event.dataTransfer !== null ) {
			preDrop();

			for (const file of event.dataTransfer.files) {
				// handle drop event
				fileParser.parseFile(file).then((res) => fileParserCallback(res));
			}

			dropCallback("File parsed");
		}
	}
</script>

<!-- is form the right aria role? -->
<span
	class={'dropZone ' + state}
	role="form"	
	aria-label="file upload dropzone"
	on:drop={handleDrop}
	on:drag={handleDrag}
>
	<p>Drop file(s) here...</p>
</span>

<style lang="scss">
	.dropZone {
		border: dashed #c5c7d0 5px;
		border-radius: 16px;
		padding: 3em 15em;
	}

	.dropZoneHover {
		border-color: #0085ff;
	}

	.dropZoneComplete {
		border-color: #00ca72;
	}
</style>

// react/src/components/fileDropper.js
import React from 'react';
import './fileDropper.css';

const DropState = {
	None: '',
	Dropping: 'dropZoneHover',
	Dropped: 'dropZoneComplete'
};

export default class FileDropBox extends React.Component {
	constructor(props) {
		super(props);

		// Default state
		this.state = {
			drop: DropState.None
		};

		this.callback = props.callback;
		this.preDropCallback = props.preDropCallback;
		this.fileParser = props.fileParserCallback;
	}

	dragHandler(event) {
		event.preventDefault();

		if (event.type === 'dragover') {
			this.setState({ drop: DropState.Dropping });
		} else if (event.type === 'dragexit') {
			this.setState({ drop: DropState.None });
		}
	}

	async dropHandler(event) {
		this.setState({ drop: DropState.Dropped });

		event.preventDefault();
		const files = event.dataTransfer.files;

		if (this.preDropCallback) {
			await this.preDropCallback();
		}

		for (const file of files) {
			// handle drop event
			this.fileParser.parseFile(file).then((res) => this.callback(res));
		}

		return;
	}

	render() {
		return (
			<div
				className={'dropZone ' + this.state.drop}
				onDrop={(e) => this.dropHandler(e)}
				onDragOver={(e) => this.dragHandler(e)}
				onDragExit={(e) => this.dragHandler(e)}
			>
				<p>Drop file(s) here...</p>
			</div>
		);
	}
}
